name: Python lint

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: eifinger/setup-rye@v2

      - name: Rye fmt --check
        run: rye fmt --check

      - name: Rye lint
        run: rye lint

    #   - name: Rye test
    #     run: |
    #         rye sync
    #         rye test